[project]
name = "backblaze"
version = "0.1.0"
description = "Multimodal Data Processing with Pixeltable and Backblaze B2"
requires-python = ">=3.10"
dependencies = [
    "boto3>=1.43.36,<1.44",
    "botocore>=1.43.36,<1.44",
    "pixeltable>=0.4.24,<0.7",
]

[dependency-groups]
dev = [
    "jupyter",
    "ipykernel",
]
